name: Reusable Deploy
# workflow_call allows you to call workflow from another workflow
# workflow_dispatch lets you run workflow manually
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact-name }}
      - name: List files
        run: ls
      - name: Outut info
        run: echo "Deploying and uploading"
